/*
 * This file is generated by jOOQ.
 */
package com.example.jooqtest.jooq.tables;


import com.example.jooqtest.jooq.Indexes;
import com.example.jooqtest.jooq.Keys;
import com.example.jooqtest.jooq.Public;
import com.example.jooqtest.jooq.tables.records.FlywayMigrationsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FlywayMigrations extends TableImpl<FlywayMigrationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.flyway_migrations</code>
     */
    public static final FlywayMigrations FLYWAY_MIGRATIONS = new FlywayMigrations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FlywayMigrationsRecord> getRecordType() {
        return FlywayMigrationsRecord.class;
    }

    /**
     * The column <code>public.flyway_migrations.installed_rank</code>.
     */
    public final TableField<FlywayMigrationsRecord, Integer> INSTALLED_RANK = createField(DSL.name("installed_rank"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.version</code>.
     */
    public final TableField<FlywayMigrationsRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.flyway_migrations.description</code>.
     */
    public final TableField<FlywayMigrationsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.type</code>.
     */
    public final TableField<FlywayMigrationsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.script</code>.
     */
    public final TableField<FlywayMigrationsRecord, String> SCRIPT = createField(DSL.name("script"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.checksum</code>.
     */
    public final TableField<FlywayMigrationsRecord, Integer> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.flyway_migrations.installed_by</code>.
     */
    public final TableField<FlywayMigrationsRecord, String> INSTALLED_BY = createField(DSL.name("installed_by"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.installed_on</code>.
     */
    public final TableField<FlywayMigrationsRecord, LocalDateTime> INSTALLED_ON = createField(DSL.name("installed_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.flyway_migrations.execution_time</code>.
     */
    public final TableField<FlywayMigrationsRecord, Integer> EXECUTION_TIME = createField(DSL.name("execution_time"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.flyway_migrations.success</code>.
     */
    public final TableField<FlywayMigrationsRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private FlywayMigrations(Name alias, Table<FlywayMigrationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private FlywayMigrations(Name alias, Table<FlywayMigrationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.flyway_migrations</code> table reference
     */
    public FlywayMigrations(String alias) {
        this(DSL.name(alias), FLYWAY_MIGRATIONS);
    }

    /**
     * Create an aliased <code>public.flyway_migrations</code> table reference
     */
    public FlywayMigrations(Name alias) {
        this(alias, FLYWAY_MIGRATIONS);
    }

    /**
     * Create a <code>public.flyway_migrations</code> table reference
     */
    public FlywayMigrations() {
        this(DSL.name("flyway_migrations"), null);
    }

    public <O extends Record> FlywayMigrations(Table<O> child, ForeignKey<O, FlywayMigrationsRecord> key) {
        super(child, key, FLYWAY_MIGRATIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FLYWAY_MIGRATIONS_S_IDX);
    }

    @Override
    public UniqueKey<FlywayMigrationsRecord> getPrimaryKey() {
        return Keys.FLYWAY_MIGRATIONS_PK;
    }

    @Override
    public FlywayMigrations as(String alias) {
        return new FlywayMigrations(DSL.name(alias), this);
    }

    @Override
    public FlywayMigrations as(Name alias) {
        return new FlywayMigrations(alias, this);
    }

    @Override
    public FlywayMigrations as(Table<?> alias) {
        return new FlywayMigrations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FlywayMigrations rename(String name) {
        return new FlywayMigrations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FlywayMigrations rename(Name name) {
        return new FlywayMigrations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FlywayMigrations rename(Table<?> name) {
        return new FlywayMigrations(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
