/*
 * This file is generated by jOOQ.
 */
package com.example.jooqtest.jooq.tables;


import com.example.jooqtest.jooq.Keys;
import com.example.jooqtest.jooq.Public;
import com.example.jooqtest.jooq.tables.records.TeacherRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Teacher extends TableImpl<TeacherRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.teacher</code>
     */
    public static final Teacher TEACHER = new Teacher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeacherRecord> getRecordType() {
        return TeacherRecord.class;
    }

    /**
     * The column <code>public.teacher.teacher_id</code>.
     */
    public final TableField<TeacherRecord, Integer> TEACHER_ID = createField(DSL.name("teacher_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.teacher.name</code>.
     */
    public final TableField<TeacherRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.teacher.department_id</code>.
     */
    public final TableField<TeacherRecord, Integer> DEPARTMENT_ID = createField(DSL.name("department_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.teacher.hire_date</code>.
     */
    public final TableField<TeacherRecord, LocalDate> HIRE_DATE = createField(DSL.name("hire_date"), SQLDataType.LOCALDATE, this, "");

    private Teacher(Name alias, Table<TeacherRecord> aliased) {
        this(alias, aliased, null);
    }

    private Teacher(Name alias, Table<TeacherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.teacher</code> table reference
     */
    public Teacher(String alias) {
        this(DSL.name(alias), TEACHER);
    }

    /**
     * Create an aliased <code>public.teacher</code> table reference
     */
    public Teacher(Name alias) {
        this(alias, TEACHER);
    }

    /**
     * Create a <code>public.teacher</code> table reference
     */
    public Teacher() {
        this(DSL.name("teacher"), null);
    }

    public <O extends Record> Teacher(Table<O> child, ForeignKey<O, TeacherRecord> key) {
        super(child, key, TEACHER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TeacherRecord, Integer> getIdentity() {
        return (Identity<TeacherRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TeacherRecord> getPrimaryKey() {
        return Keys.TEACHER_PKEY;
    }

    @Override
    public List<ForeignKey<TeacherRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEACHER__TEACHER_DEPARTMENT_ID_FKEY);
    }

    private transient Department _department;

    /**
     * Get the implicit join path to the <code>public.department</code> table.
     */
    public Department department() {
        if (_department == null)
            _department = new Department(this, Keys.TEACHER__TEACHER_DEPARTMENT_ID_FKEY);

        return _department;
    }

    @Override
    public Teacher as(String alias) {
        return new Teacher(DSL.name(alias), this);
    }

    @Override
    public Teacher as(Name alias) {
        return new Teacher(alias, this);
    }

    @Override
    public Teacher as(Table<?> alias) {
        return new Teacher(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Teacher rename(String name) {
        return new Teacher(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Teacher rename(Name name) {
        return new Teacher(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Teacher rename(Table<?> name) {
        return new Teacher(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super Integer, ? super LocalDate, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super Integer, ? super LocalDate, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
