/*
 * This file is generated by jOOQ.
 */
package com.example.jooqtest.jooq;


import com.example.jooqtest.jooq.tables.Course;
import com.example.jooqtest.jooq.tables.Department;
import com.example.jooqtest.jooq.tables.Enrollment;
import com.example.jooqtest.jooq.tables.FlywayMigrations;
import com.example.jooqtest.jooq.tables.Student;
import com.example.jooqtest.jooq.tables.Teacher;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.course</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.department</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>public.enrollment</code>.
     */
    public final Enrollment ENROLLMENT = Enrollment.ENROLLMENT;

    /**
     * The table <code>public.flyway_migrations</code>.
     */
    public final FlywayMigrations FLYWAY_MIGRATIONS = FlywayMigrations.FLYWAY_MIGRATIONS;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.teacher</code>.
     */
    public final Teacher TEACHER = Teacher.TEACHER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Course.COURSE,
            Department.DEPARTMENT,
            Enrollment.ENROLLMENT,
            FlywayMigrations.FLYWAY_MIGRATIONS,
            Student.STUDENT,
            Teacher.TEACHER
        );
    }
}
