/*
 * This file is generated by jOOQ.
 */
package com.example.jooqtest.jooq;


import com.example.jooqtest.jooq.tables.Course;
import com.example.jooqtest.jooq.tables.Department;
import com.example.jooqtest.jooq.tables.Enrollment;
import com.example.jooqtest.jooq.tables.FlywayMigrations;
import com.example.jooqtest.jooq.tables.Student;
import com.example.jooqtest.jooq.tables.Teacher;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.course</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.department</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>public.enrollment</code>.
     */
    public static final Enrollment ENROLLMENT = Enrollment.ENROLLMENT;

    /**
     * The table <code>public.flyway_migrations</code>.
     */
    public static final FlywayMigrations FLYWAY_MIGRATIONS = FlywayMigrations.FLYWAY_MIGRATIONS;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.teacher</code>.
     */
    public static final Teacher TEACHER = Teacher.TEACHER;
}
